### ISSUE TITLE
Nothing happlen under resources

### ISSUE THREAD

**Issue by bao-qian** [EgorBo/Xamaridea#1]
Hi,
This is a fantastic plugin.
But
There is no xml/axml under resources folder after opning Android Studio.

I tried use lower case file name and rename axml to xml, no help.
![2014-12-31_19-06-05](https://cloud.githubusercontent.com/assets/1169912/5589864/2a2f2c4c-9120-11e4-8e26-ab248809434a.png)
![2014-12-31_19-06-18](https://cloud.githubusercontent.com/assets/1169912/5589866/2bc0dc72-9120-11e4-809f-5ede0092bd91.png)

Any help?

Installed from Visual Studio Gallery.
Default template.
OS Windows 8.1 X64
Android Studio:1.0.2 x64
Visual Studio: 2013 Ultimate update 4

**Comment by EgorBo** [comment]
@happlebao that's because of gradle compatibility issues. I'll fix it in a minute. Thanks for the feedback!

**Comment by EgorBo** [comment]
Fixed by updating required gradle version (and removed proguard from gradle.build).
0.4 version is available at https://visualstudiogallery.msdn.microsoft.com/9f5a516a-f4d0-4228-9d25-d0273abebf33

**Comment by bao-qian** [comment]
Thanks for your fix.
But you forget to change  the default template.
1. Change the gradle version in `builde.gradle` of project from 0.13.2 to 1.0.0
2. Change `runProguard` in `builde.grade` of app to `minifyEnabled`.

**Comment by bao-qian** [comment]
Why use zip instead of folder form template? zip can't use version control.
It looks like you didn't commit your newest change to Github?

**Comment by EgorBo** [comment]
@happlebao indeed. I didn't push it. (and yes, I changed version to 1.0.0 and removed runProguard).
PS: it is nice idea to store template without zipping. and make an arhive during compilation, thanks!

**Comment by bao-qian** [comment]
@EgorBo There are something wrong in the upgrade mechanism. If you just upgrade inside Visual Studio, there will no `Template_v.0.4`. I finally got it by reinstall the extension.
To dismiss the warning dialog in idea, you need update

``` ruby
distributionUrl=https\://services.gradle.org/distributions/gradle-2.1-all.zip
```

to

``` ruby
distributionUrl=https\://services.gradle.org/distributions/gradle-2.2.1-all.zip
```

in `gradle-wrapper.properties`

**Comment by EgorBo** [comment]
Updated to gradle-3.3.0
