### ISSUE TITLE
Visual Studio 2017RC support

### ISSUE THREAD

**Issue by nnddnn** [EgorBo/Xamaridea#8]
Please, update your extensions for Visual Studio 2017RC !!

**Comment by moaeadw** [comment]
added PR for this.
you can also download from here if you don't wanna compile.
[https://drive.google.com/open?id=0BysjCKi8s7PvY0ZSTlVsT3g0Mlk](https://drive.google.com/open?id=0BysjCKi8s7PvY0ZSTlVsT3g0Mlk)

**Comment by vmsanchez05** [comment]
Please update for VS 2017!!

**Comment by EgorBo** [comment]
Done! :-)
